name = "NumericalRelaxation"
uuid = "82303a6c-a702-44d7-938a-15dad61d8a03"
authors = ["Maximilian Köhler <maximilian.koehler@ruhr-uni-bochum.de>",
           "Timo Neumeier <timo.neumeier@math.uni-augsburg.de>",
           "Jan Sebastian Melchior <Jan.Melchior-a1m@ruhr-uni-bochum.de>",
           "Contributors"]
version = "0.1.0"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
